// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWwq0zGaEIB1Au4rkb8HouAD_ko4ozfEs',
    appId: '1:932395257939:web:21f638c40f344debfeb6a6',
    messagingSenderId: '932395257939',
    projectId: 'flash-chat-37226',
    authDomain: 'flash-chat-37226.firebaseapp.com',
    storageBucket: 'flash-chat-37226.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz6gkSRP80iaRuCynUAv_wRQCAuOpWeek',
    appId: '1:932395257939:android:2d5b0f69cab14426feb6a6',
    messagingSenderId: '932395257939',
    projectId: 'flash-chat-37226',
    storageBucket: 'flash-chat-37226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlyEceea7lqOMeRmjdnH6CEuloP12f4Ig',
    appId: '1:932395257939:ios:b4fc98408c968f44feb6a6',
    messagingSenderId: '932395257939',
    projectId: 'flash-chat-37226',
    storageBucket: 'flash-chat-37226.appspot.com',
    iosClientId: '932395257939-mu9kauahi69vgogvb1jur8g3s0m28deg.apps.googleusercontent.com',
    iosBundleId: 'tech.mavica.flashchat.flashChat',
  );
}
